### ISSUE TITLE
"Object reference not set" exception in case of no connectivity

### ISSUE THREAD

**Issue by Ross-cz** [gopaycommunity/gopay-dotnet-api#11]
When there is no connection, I get "Object reference not set" exception.
Call stack:
   at GoPay.GPConnector.Deserialize[T](String Content)
   at GoPay.GPConnector.GetAppToken(String scope)

**Comment by FSichinger** [comment]
Due to PCI-DSS we are upgrating to TLS 1.2. 
Right now TLS 1.2 is used only in our integration environment. Our production servers will start using TLS 1.2 in July 2018.

Right now you have to set security protocol manager to use TLS 1.2
`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`
or upgrade our sdk to version 1.1.8
